<a href="https://colab.research.google.com/github/Dares18/ProcessingData/blob/main/DataProsce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the dataset
dataset = pd.read_csv('ValorantPlayer.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
#Cek Attribute
print(x)

[[  1  13   5   1   1]
 [  2  13   4   1   1]
 [  3  14   3   1   1]
 ...
 [498   7   2   5   0]
 [499  19  10   2   0]
 [500   6   4   2   0]]


In [4]:
#Cek Label
print(y)

['High' 'High' 'High' 'High' 'High' 'High' 'Medium' 'High' 'High' 'High'
 'Medium' 'Low' 'Medium' 'High' 'Medium' 'High' 'High' 'High' 'High' 'Low'
 'Low' 'Medium' 'Low' 'Low' 'High' 'High' 'High' 'Low' 'High' 'High' 'Low'
 'Low' 'Medium' 'Low' 'Medium' 'Low' 'Low' 'Low' 'Medium' 'Medium' 'High'
 'Low' 'Low' 'Low' 'Low' 'High' 'Medium' 'Medium' 'Medium' 'Medium' 'High'
 'Medium' 'High' 'Medium' 'Low' 'MEdium' 'High' 'Medium' 'Medium' 'Low'
 'High' 'High' 'Medium' 'High' 'High' 'Medium' 'Medium' 'High' 'High'
 'Low' 'High' 'High' 'HIgh' 'Medium' 'Medium' 'Medium' 'Low' 'Low' 'Low'
 'Low' 'Low' 'High' 'Low' 'Low' 'Medium' 'High' 'High' 'Medium' 'Low'
 'High' 'High' 'Medium' 'High' 'Medium' 'Medium' 'Medium' 'Low' 'Low'
 'Low' 'Low' 'Low' 'Medium' 'High' 'High' 'High' 'High' 'Low' 'Low' 'Low'
 'High' 'Medium' 'Low' 'Low' 'Low' 'Low' 'Medium' 'High' 'High' 'Medium'
 'Low' 'Low' 'Low' 'Low' 'Medium' 'High' 'Medium' 'low' 'High' 'Low'
 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Low' 'High

In [15]:
#Encoding data kategori (Atribut)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

print(X)

[[ 1.  0.  0. ...  5.  1.  1.]
 [ 0.  1.  0. ...  4.  1.  1.]
 [ 0.  0.  1. ...  3.  1.  1.]
 ...
 [ 0.  0.  0. ...  2.  5.  0.]
 [ 0.  0.  0. ... 10.  2.  0.]
 [ 0.  0.  0. ...  4.  2.  0.]]


In [6]:
#Encoding data kategori (Class/Label)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print (y)

[1 1 1 1 1 1 4 1 1 1 4 2 4 1 4 1 1 1 1 2 2 4 2 2 1 1 1 2 1 1 2 2 4 2 4 2 2
 2 4 4 1 2 2 2 2 1 4 4 4 4 1 4 1 4 2 3 1 4 4 2 1 1 4 1 1 4 4 1 1 2 1 1 0 4
 4 4 2 2 2 2 2 1 2 2 4 1 1 4 2 1 1 4 1 4 4 4 2 2 2 2 2 4 1 1 1 1 2 2 2 1 4
 2 2 2 2 4 1 1 4 2 2 2 2 4 1 4 5 1 2 4 4 4 4 4 2 1 1 2 2 2 1 4 2 2 2 4 4 4
 4 1 1 1 2 2 1 4 1 1 4 1 2 2 4 4 2 1 4 1 2 2 2 1 1 5 5 5 5 2 4 4 4 4 2 4 2
 1 4 2 4 2 2 4 2 2 2 4 4 4 1 1 1 2 2 2 1 1 2 4 2 4 2 2 4 2 4 2 2 4 4 2 2 1
 5 5 4 5 4 4 4 1 4 4 4 2 4 1 1 2 2 2 2 2 2 4 4 2 2 2 2 2 2 2 2 4 1 4 4 2 4
 4 4 2 4 1 2 2 4 2 4 2 2 5 4 4 2 2 1 1 1 2 2 4 4 2 4 2 4 2 2 4 2 4 2 4 4 2
 2 2 2 1 1 1 4 2 1 4 4 4 2 1 1 2 4 4 2 2 2 2 2 1 4 4 2 4 1 2 4 2 2 4 2 4 2
 2 2 4 2 2 1 2 2 4 2 4 2 4 1 2 1 1 1 1 1 2 4 4 2 2 4 4 2 1 4 4 2 2 2 4 2 1
 1 4 4 2 4 4 2 2 2 2 2 2 4 4 4 2 4 4 2 2 2 2 4 2 2 1 2 4 2 2 2 4 1 2 2 2 2
 2 2 2 4 2 2 2 1 4 4 4 2 2 2 4 2 4 4 2 2 2 2 4 1 4 4 2 2 4 4 4 4 2 2 1 4 2
 4 4 2 2 4 4 2 2 1 4 4 2 2 2 2 4 2 2 2 4 4 4 4 4 4 1 2 1 2 2 2 4 2 2 1 4 2
 2 2 2 2 4 4 2 2 2 2 2 4 

In [7]:
#Membagi dataset ke dalam training set dan test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
print(X_train)

[[ 0.  0.  0. ...  2.  0.  0.]
 [ 0.  0.  0. ...  3.  1.  0.]
 [ 0.  0.  0. ...  3.  1.  0.]
 ...
 [ 0.  0.  0. ...  8.  1.  0.]
 [ 0.  0.  0. ... 12.  6.  0.]
 [ 0.  0.  0. ...  3.  2.  0.]]


In [9]:
print(X_test)

[[ 0.  0.  0. ...  8.  5.  0.]
 [ 0.  0.  0. ...  3.  1.  0.]
 [ 0.  0.  0. ...  3.  1.  0.]
 ...
 [ 0.  0.  0. ... 12.  6.  0.]
 [ 0.  0.  0. ...  3.  1.  0.]
 [ 0.  0.  0. ...  2.  1.  0.]]


In [10]:
print(y_train)

[2 4 4 4 2 2 2 2 4 4 2 4 4 2 4 4 4 1 1 4 1 2 1 4 4 2 2 4 2 4 2 4 2 1 4 2 2
 4 4 5 2 2 4 4 1 4 4 4 2 2 1 1 2 4 2 4 2 1 2 2 4 1 2 2 2 2 1 2 2 4 2 1 2 4
 1 1 2 2 4 4 2 2 2 4 1 2 2 2 4 4 4 1 4 2 1 2 4 2 4 2 2 2 4 2 2 2 4 1 5 1 4
 4 4 2 4 2 2 4 2 1 2 1 2 1 1 1 2 2 2 2 4 1 4 4 1 4 1 4 2 4 1 2 2 4 2 2 4 4
 2 2 1 4 2 2 4 2 4 2 2 5 2 4 1 1 4 2 2 4 4 4 1 1 2 4 5 2 2 2 2 2 2 2 1 4 1
 4 2 4 2 5 1 2 2 3 2 2 4 4 2 4 2 2 1 2 4 4 2 1 2 2 2 4 2 4 2 1 1 2 1 2 1 2
 1 1 4 1 4 4 4 4 1 2 4 2 2 4 2 2 1 4 2 2 4 2 5 2 2 1 4 2 2 1 2 4 2 1 4 1 4
 2 1 4 2 2 2 2 4 2 2 2 2 4 1 4 4 2 2 2 2 2 4 1 2 1 2 1 2 1 1 4 4 2 4 2 1 4
 4 1 4 4 2 4 1 4 2 4 2 2 2 4 2 1 4 2 2 4 2 2 2 5 4 2 2 1 2 4 2 4 4 1 4 1 1
 2 4 1 2 2 1 2 2 2 1 4 4 2 4 4 2 2 4 4 4 2 2 4 2 4 1 4 2 2 1 1 2 4 1 1 2 2
 1 1 2 2 1 2 1 4 1 2 1 1 4 4 2 2 1 2 4 2 4 4 4 2 2 4 0 2 1 2]


In [11]:
print(y_test)

[1 2 4 1 4 4 1 2 2 1 2 2 2 4 4 2 2 4 2 4 4 4 2 4 4 4 4 2 5 2 4 4 2 4 4 2 1
 1 4 1 4 1 4 2 2 4 2 4 2 1 2 4 1 2 4 4 2 1 1 1 2 1 2 2 2 2 2 2 4 4 4 1 4 1
 2 4 2 2 2 1 4 1 2 4 1 5 4 2 2 2 2 2 4 4 2 2 2 1 1 4]


In [12]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [13]:
print(X_train)

[[ 0.          0.          0.         ... -0.78225491 -1.1209054
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647 -0.41259235
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647 -0.41259235
  -0.16815955]
 ...
 [ 0.          0.          0.         ...  1.59421569 -0.41259235
  -0.16815955]
 [ 0.          0.          0.         ...  3.17852943  3.12897289
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647  0.2957207
  -0.16815955]]


In [14]:
print(X_test)

[[ 0.          0.          0.         ...  1.59421569  2.42065984
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647 -0.41259235
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647 -0.41259235
  -0.16815955]
 ...
 [ 0.          0.          0.         ...  3.17852943  3.12897289
  -0.16815955]
 [ 0.          0.          0.         ... -0.38617647 -0.41259235
  -0.16815955]
 [ 0.          0.          0.         ... -0.78225491 -0.41259235
  -0.16815955]]
